version: '3.3'

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./database/danp.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: header-backend
    ports:
      - 8080:8080

  frontend:
    image: header-frontend
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      CI: 'true'
    ports:
      - 3000:3000